apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-kubernetes-local.fullname" . }}
  labels:
    {{- include "helm-kubernetes-local.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq "NodePort" .Values.service.type }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.debugPort }}
      targetPort: http
      {{- if eq "NodePort" .Values.service.type }}
      nodePort: {{ .Values.service.debugNodePort }}
      {{- end }}
      protocol: TCP
      name: debug
  selector:
    {{- include "helm-kubernetes-local.selectorLabels" . | nindent 4 }}
